[tools]
rust = { version = "1.96.1", components = "clippy,rustfmt" }

[tasks.ci]
depends = ["test", "clippy", "format-check"]

[tasks.test]
run = "cargo test"

[tasks."test:update"]
depends = ["TRYCMD=overwrite test"]

[tasks.clippy]
sources = ["src/**/*.rs", "Cargo.toml", "Cargo.lock"]
run = "cargo clippy -- -D warnings"

[tasks.format]
run = "cargo fmt"

[tasks.format-check]
sources = ["src/**/*.rs", "Cargo.toml", "Cargo.lock"]
run = "cargo fmt --check"
